version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    image: sl-server
    container_name: "sl-server"
    ports:
      - "8080:8080"
    command: "api"
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/go/bin/deployments/
    logging:
      driver: "json-file"
      options:
        max-size: 300m

  postgres:
    image: postgres:15
    container_name: sl-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: url-shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: sl-redis
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
